<h1 style="text-align:center;">Classic &amp; Ceiling Rail Configurator</h1>
<h3 style="margin:1.5em auto;width:75%;">Set up the perfect Art Hanging System for your needs in a simple, step-by-step format. <br style="line-height:1.5;">Choose color, quantity, and more, then add it all to your cart at once! <br style="line-height:1.5;">Get everything you need in one place, with Mbs Hanging Systems.</h3>
<!-- <h4 id="subtotal" style="text-align:center;font-style:normal;">$0.00</h4> -->
<p style="text-align:center;">
	<span id="no-products" class="availability notice" style="display:none;font-style:normal;font-weight:normal;">No Products have been added to your selection.<br><br></span>
	<input type="submit" title="Add to Package" class="button btn-cart" id="finalize" value="Checkout"></input>
</p>
<div class="home-container grid">
	<div class="cd-hero">

		<div class="cd-slider-nav configurator-wrapper">
			<nav class="configurator">
				<ul class="choices">
					<li class="selected"><a href="#0">Art Hanging Rails</a></li>
					<li><a href="#0">Hanging Cables/Rods</a></li>
					<!-- <li><a href="#0">Hanging Rods</a></li> -->
					<li><a href="#0">Cable &amp; Rod Hooks</a></li>
					<!-- <li><a href="#0">Rod Hooks</a></li> -->
					<li><a href="#0">Accessories</a></li>
					<li><a href="#0">Installation Hardware</a></li>
				</ul>
			</nav>
		</div>

		<!-- <ul class="cd-slider-nav" style="margin:0 auto;width:75%;">
			<li style="float:left;"><a href="#0" class="cd-prev inactive button btn-cart" id="slide1">Prev</a></li>
			<li style="float:right;"><a href="#0" class="cd-prev next button btn-cart" id="slide2">Next</a></li>
			<li style="display:none;"><a href="#0" class="cd-prev next button btn-cart" id="slide3">Next</a></li>
			<li style="display:none;"><a href="#0" class="cd-prev next button btn-cart" id="slide4">Next</a></li>
			<li style="display:none;"><a href="#0" class="cd-prev next button btn-cart" id="slide5">Next</a></li>
		</ul> -->

		<ul class="cd-hero-slider" id="configurator-panels" style="clear:both;">

			<!-- RAILS TAB -->
			<li class="rails selected">

			<?php
				$rails = Mage::getModel('catalog/category')->load(206)->getProductCollection()
										 ->addAttributeToSelect('*')
										 ->addAttributeToFilter('status', 1)
										 ->addAttributeToFilter('visibility', 4);
				foreach($rails as $rail) { ?>
				<div class="configurator-item-wrapper">
					<div class="configurator-item">
						<div class="img-wrapper">
							<span class="short-desc"><span><?php echo $rail->getShortDescription(); ?></span></span>
							<img src="<?php echo Mage::helper('catalog/image')->init($rail, 'small_image')->resize(200,200); ?>" alt="<?php echo $rail->getName(); ?>">
						</div>
						<h3><?php echo $rail->getName(); ?></h3>
						<?php 
						$allProducts = '';
						if($rail->isConfigurable()) {
							$attributes = $rail->getTypeInstance(true)->getConfigurableAttributes($rail);

							if(count($attributes)) { ?>
							<ul>
								<?php foreach ($attributes as $attribute) {
									$pAtt = $attribute->getProductAttribute();
									$allProducts = $rail->getTypeInstance(true)->getUsedProducts(null, $rail);
									$frontValues = array(); ?>
								<li style="padding: 0 1.25em;"><?php echo $pAtt->getFrontendLabel() ?>
									<select id="choice<?php echo $rail->getId() ?>" data-id="<?php echo $rail->getFinalPrice() ?>" style="float:right;" onchange="getChoice(this,<?php echo $rail->getData('entity_id') ?>)">
										<?php foreach($allProducts as $p) {
											if(!$p->isSaleable()) continue;
											$out = $p->getAttributeText($pAtt->getName());
											$sku = $p->getData('entity_id');
											$choicePrice = Mage::getModel('catalog/product')->load($sku)->getFinalPrice();
											$priceDiff = $choicePrice - $rail->getFinalPrice();
											if($priceDiff > 0){$out = $out." + $".$priceDiff;}
											$frontValues[$out] = $out; ?>
											<option id="<?php echo $sku ?>" data-id="<?php echo $priceDiff; ?>"><?php echo $frontValues[$out] ?></option>
										<?php } ?>
									</select>
								</li>
								<?php } ?>
							</ul>
							<?php } ?>
						<?php } ?>
						<p>
							<span id="p<?php echo $rail->getData('entity_id') ?>">
								<label for="qty<?php echo $rail->getProductId() ?>" class="qty-label">Qty</label>
								<input type="number" min="0" name="product[<?php echo $rail->getProductId() ?>][qty]<?php echo $rail->getProductId() ?>" id="qty<?php if($rail->isConfigurable()) {echo $allProducts[0]->getData('entity_id');} else {echo $rail->getData('entity_id');} ?>" class="input-number" value="0">
							</span>
							<span id="span<?php echo $rail->getData('entity_id') ?>">
								<span class="price" id="price<?php echo $rail->getId() ?>"><?php echo Mage::helper('core')->currency($rail->getFinalPrice(), true, false); ?></span>
								<input type="checkbox" id="<?php if($rail->isConfigurable()) {echo $allProducts[0]->getData('entity_id');} else {echo $rail->getData('entity_id');} ?>">
							</span>
						</p>
					</div>
				</div>
				<?php	}
			?>
			</li>


			<!-- CABLES TAB -->
			<li class="cables">
			<?php
				$cables = Mage::getModel('catalog/category')->load(209)->getProductCollection()
										 ->addAttributeToSelect('*')
										 ->addAttributeToFilter('status', 1)
										 ->addAttributeToFilter('visibility', 4);
				foreach($cables as $cable) { ?>
				<div class="configurator-item-wrapper">
					<div class="configurator-item">
						<div class="img-wrapper">
							<span class="short-desc"><span><?php echo $cable->getShortDescription(); ?></span></span>
							<img src="<?php echo Mage::helper('catalog/image')->init($cable, 'small_image')->resize(200,200); ?>" alt="<?php echo $cable->getName(); ?>">
						</div>
						<h3><?php echo $cable->getName(); ?></h3>
						<?php if($cable->isConfigurable()) {
							$attributes = $cable->getTypeInstance(true)->getConfigurableAttributes($cable);
							if(count($attributes)) { ?>
							<ul>
								<?php foreach ($attributes as $attribute) {
									$pAtt = $attribute->getProductAttribute();
									$allProducts = $cable->getTypeInstance(true)->getUsedProducts(null, $cable);
									$frontValues = array(); ?>
								<li style="padding: 0 1.25em;"><?php echo $pAtt->getFrontendLabel() ?>
									<select id="choice<?php echo $cable->getId() ?>" data-id="<?php echo $cable->getFinalPrice() ?>" style="float:right;" onchange="getChoice(this,<?php echo $cable->getData('entity_id') ?>)">
										<?php foreach($allProducts as $p) {
											if(!$p->isSaleable()) continue;
											$out = $p->getAttributeText($pAtt->getName());
											$sku = $p->getData('entity_id');
											$choicePrice = Mage::getModel('catalog/product')->load($sku)->getFinalPrice();
											$priceDiff = $choicePrice - $cable->getFinalPrice();
											if($priceDiff > 0){$out = $out." + $".$priceDiff;}
											$frontValues[$out] = $out; ?>
											<option id="<?php echo $p->getData('entity_id'); ?>" data-id="<?php echo $priceDiff; ?>"><?php echo $frontValues[$out] ?></option>
										<?php } ?>
									</select>
								</li>
								<?php } ?>
							</ul>
							<?php } ?>
						<?php } ?>
						<p>
							<span id="p<?php echo $cable->getData('entity_id') ?>">
								<label for="qty<?php echo $cable->getProductId() ?>" class="qty-label">Qty</label>
								<input type="number" min="0" name="product[<?php echo $cable->getProductId() ?>][qty]<?php echo $cable->getProductId() ?>" id="qty<?php if($cable->isConfigurable()) {echo $allProducts[0]->getData('entity_id');} else {echo $cable->getData('entity_id');} ?>" class="input-number" value="0">
							</span>
							<span id="span<?php echo $cable->getData('entity_id') ?>">
								<span class="price" id="price<?php echo $cable->getId() ?>"><?php echo Mage::helper('core')->currency($cable->getFinalPrice(), true, false); ?></span>
								<input type="checkbox" id="<?php if($cable->isConfigurable()) {echo $allProducts[0]->getData('entity_id');} else {echo $cable->getData('entity_id');} ?>">
							</span>
						</p>
					</div>
				</div>
				<?php }
			?>
			<!-- </li> -->


			<!-- RODS TAB -->
			<!-- <li class="rods"> -->
			<?php
				$rods = Mage::getModel('catalog/category')->load(208)->getProductCollection()
										 ->addAttributeToSelect('*')
										 ->addAttributeToFilter('status', 1)
										 ->addAttributeToFilter('visibility', 4);
				foreach($rods as $rod) { ?>
				<div class="configurator-item-wrapper">
					<div class="configurator-item">
						<div class="img-wrapper">
							<span class="short-desc"><span><?php echo $rod->getShortDescription(); ?></span></span>
							<img src="<?php echo Mage::helper('catalog/image')->init($rod, 'small_image')->resize(200,200); ?>" alt="<?php echo $rod->getName(); ?>">
						</div>
						<h3><?php echo $rod->getName(); ?></h3>
						<?php if($rod->isConfigurable()) {
							$attributes = $rod->getTypeInstance(true)->getConfigurableAttributes($rod);
							if(count($attributes)) { ?>
							<ul>
								<?php foreach ($attributes as $attribute) {
									$pAtt = $attribute->getProductAttribute();
									$allProducts = $rod->getTypeInstance(true)->getUsedProducts(null, $rod);
									$frontValues = array(); ?>
								<li style="padding: 0 1.25em;"><?php echo $pAtt->getFrontendLabel() ?>
									<select id="choice<?php echo $rod->getId() ?>" data-id="<?php echo $rod->getFinalPrice() ?>" style="float:right;" onchange="getChoice(this,<?php echo $rod->getData('entity_id') ?>)">
										<?php foreach($allProducts as $p) {
											if(!$p->isSaleable()) continue;
											$out = $p->getAttributeText($pAtt->getName());
											$sku = $p->getData('entity_id');
											$choicePrice = Mage::getModel('catalog/product')->load($sku)->getFinalPrice();
											$priceDiff = $choicePrice - $rod->getFinalPrice();
											if($priceDiff > 0){$out = $out." + $".$priceDiff;}
											$frontValues[$out] = $out; ?>
											<option id="<?php echo $p->getData('entity_id'); ?>" data-id="<?php echo $priceDiff; ?>"><?php echo $frontValues[$out] ?></option>
										<?php } ?>
									</select>
								</li>
								<?php } ?>
							</ul>
							<?php } ?>
						<?php } ?>
						<p>
							<span id="p<?php echo $rod->getData('entity_id') ?>">
								<label for="qty<?php echo $rod->getProductId() ?>" class="qty-label">Qty</label>
								<input type="number" min="0" name="product[<?php echo $rod->getProductId() ?>][qty]<?php echo $rod->getProductId() ?>" id="qty<?php if($rod->isConfigurable()) {echo $allProducts[0]->getData('entity_id');} else {echo $rod->getData('entity_id');} ?>" class="input-number" value="0">
							</span>
							<span id="span<?php echo $rod->getData('entity_id') ?>">
								<span class="price" id="price<?php echo $rod->getId() ?>"><?php echo Mage::helper('core')->currency($rod->getFinalPrice(), true, false); ?></span>
								<input type="checkbox" id="<?php if($rod->isConfigurable()) {echo $allProducts[0]->getData('entity_id');} else {echo $rod->getData('entity_id');} ?>">
							</span>
						</p>
					</div>
				</div>
				<?php }
			?>
			</li>


			<!-- HOOKS TAB -->
			<li class="hooks">
			<?php
				$hooks = Mage::getModel('catalog/category')->load(210)->getProductCollection()
										 ->addAttributeToSelect('*')
										 ->addAttributeToFilter('status', 1)
										 ->addAttributeToFilter('visibility', 4);
				foreach($hooks as $hook) { ?>
				<div class="configurator-item-wrapper">
					<div class="configurator-item">
						<div class="img-wrapper">
							<span class="short-desc"><span><?php echo $hook->getShortDescription(); ?></span></span>
							<img src="<?php echo Mage::helper('catalog/image')->init($hook, 'small_image')->resize(200,200); ?>" alt="<?php echo $hook->getName(); ?>">
						</div>
						<h3><?php echo $hook->getName(); ?></h3>
						<?php if($hook->isConfigurable()) {
							$attributes = $hook->getTypeInstance(true)->getConfigurableAttributes($hook);
							if(count($attributes)) { ?>
							<ul>
								<?php foreach ($attributes as $attribute) {
									$pAtt = $attribute->getProductAttribute();
									$allProducts = $hook->getTypeInstance(true)->getUsedProducts(null, $hook);
									$frontValues = array(); ?>
								<li style="padding: 0 1.25em;"><?php echo $pAtt->getFrontendLabel() ?>
									<select id="choice<?php echo $hook->getId() ?>" data-id="<?php echo $hook->getFinalPrice() ?>" style="float:right;" onchange="getChoice(this,<?php echo $hook->getData('entity_id') ?>)">
										<?php foreach($allProducts as $p) {
											if(!$p->isSaleable()) continue;
											$out = $p->getAttributeText($pAtt->getName());
											$sku = $p->getData('entity_id');
											$choicePrice = Mage::getModel('catalog/product')->load($sku)->getFinalPrice();
											$priceDiff = $choicePrice - $hook->getFinalPrice();
											if($priceDiff > 0){$out = $out." + $".$priceDiff;}
											$frontValues[$out] = $out; ?>
											<option id="<?php echo $p->getData('entity_id'); ?>" data-id="<?php echo $priceDiff; ?>"><?php echo $frontValues[$out] ?></option>
										<?php } ?>
									</select>
								</li>
								<?php } ?>
							</ul>
							<?php } ?>
						<?php } ?>
						<p>
							<span id="p<?php echo $hook->getData('entity_id') ?>">
								<label for="qty<?php echo $hook->getProductId() ?>" class="qty-label">Qty</label>
								<input type="number" min="0" name="product[<?php echo $hook->getProductId() ?>][qty]<?php echo $hook->getProductId() ?>" id="qty<?php if($hook->isConfigurable()) {echo $allProducts[0]->getData('entity_id');} else {echo $hook->getData('entity_id');} ?>" class="input-number" value="0">
							</span>
							<span id="span<?php echo $hook->getData('entity_id') ?>">
								<span class="price" id="price<?php echo $hook->getId() ?>"><?php echo Mage::helper('core')->currency($hook->getFinalPrice(), true, false); ?></span>
								<input type="checkbox" id="<?php if($hook->isConfigurable()) {echo $allProducts[0]->getData('entity_id');} else {echo $hook->getData('entity_id');} ?>">
							</span>
						</p>
					</div>
				</div>
				<?php }
			?>
			<!-- </li> -->


			<!-- HOOKS TAB -->
			<!-- <li class="hooks"> -->
			<?php
				$hooks = Mage::getModel('catalog/category')->load(198)->getProductCollection()
										 ->addAttributeToSelect('*')
										 ->addAttributeToFilter('status', 1)
										 ->addAttributeToFilter('visibility', 4);
				foreach($hooks as $hook) { ?>
				<div class="configurator-item-wrapper">
					<div class="configurator-item">
						<div class="img-wrapper">
							<span class="short-desc"><span><?php echo $hook->getShortDescription(); ?></span></span>
							<img src="<?php echo Mage::helper('catalog/image')->init($hook, 'small_image')->resize(200,200); ?>" alt="<?php echo $hook->getName(); ?>">
						</div>
						<h3><?php echo $hook->getName(); ?></h3>
						<?php if($hook->isConfigurable()) {
							$attributes = $hook->getTypeInstance(true)->getConfigurableAttributes($hook);
							if(count($attributes)) { ?>
							<ul>
								<?php foreach ($attributes as $attribute) {
									$pAtt = $attribute->getProductAttribute();
									$allProducts = $hook->getTypeInstance(true)->getUsedProducts(null, $hook);
									$frontValues = array(); ?>
								<li style="padding: 0 1.25em;"><?php echo $pAtt->getFrontendLabel() ?>
									<select id="choice<?php echo $hook->getId() ?>" data-id="<?php echo $hook->getFinalPrice() ?>" style="float:right;" onchange="getChoice(this,<?php echo $hook->getData('entity_id') ?>)">
										<?php foreach($allProducts as $p) {
											if(!$p->isSaleable()) continue;
											$out = $p->getAttributeText($pAtt->getName());
											$sku = $p->getData('entity_id');
											$choicePrice = Mage::getModel('catalog/product')->load($sku)->getFinalPrice();
											$priceDiff = $choicePrice - $hook->getFinalPrice();
											if($priceDiff > 0){$out = $out." + $".$priceDiff;}
											$frontValues[$out] = $out; ?>
											<option id="<?php echo $p->getData('entity_id'); ?>" data-id="<?php echo $priceDiff; ?>"><?php echo $frontValues[$out] ?></option>
										<?php } ?>
									</select>
								</li>
								<?php } ?>
							</ul>
							<?php } ?>
						<?php } ?>
						<p>
							<span id="p<?php echo $hook->getData('entity_id') ?>">
								<label for="qty<?php echo $hook->getProductId() ?>" class="qty-label">Qty</label>
								<input type="number" min="0" name="product[<?php echo $hook->getProductId() ?>][qty]<?php echo $hook->getProductId() ?>" id="qty<?php if($hook->isConfigurable()) {echo $allProducts[0]->getData('entity_id');} else {echo $hook->getData('entity_id');} ?>" class="input-number" value="0">
							</span>
							<span id="span<?php echo $hook->getData('entity_id') ?>">
								<span class="price" id="price<?php echo $hook->getId() ?>"><?php echo Mage::helper('core')->currency($hook->getFinalPrice(), true, false); ?></span>
								<input type="checkbox" id="<?php if($hook->isConfigurable()) {echo $allProducts[0]->getData('entity_id');} else {echo $hook->getData('entity_id');} ?>">
							</span>
						</p>
					</div>
				</div>
				<?php }
			?>
			</li>


			<!-- ACCESSORIES TAB -->
			<li class="accessories">
			<?php
				$accessories = Mage::getModel('catalog/category')->load(200)->getProductCollection()
										 ->addAttributeToSelect('*')
										 ->addAttributeToFilter('status', 1)
										 ->addAttributeToFilter('visibility', 4);
				foreach($accessories as $accessory) { ?>
				<div class="configurator-item-wrapper">
					<div class="configurator-item">
						<div class="img-wrapper">
							<span class="short-desc"><span><?php echo $accessory->getShortDescription(); ?></span></span>
							<img src="<?php echo Mage::helper('catalog/image')->init($accessory, 'small_image')->resize(200,200); ?>" alt="<?php echo $accessory->getName(); ?>">
						</div>
						<h3><?php echo $accessory->getName(); ?></h3>
						<?php if($accessory->isConfigurable()) {
							$attributes = $accessory->getTypeInstance(true)->getConfigurableAttributes($accessory);
							if(count($attributes)) { ?>
							<ul>
								<?php foreach ($attributes as $attribute) {
									$pAtt = $attribute->getProductAttribute();
									$allProducts = $accessory->getTypeInstance(true)->getUsedProducts(null, $accessory);
									$frontValues = array(); ?>
								<li style="padding: 0 1.25em;"><?php echo $pAtt->getFrontendLabel() ?>
									<select id="choice<?php echo $accessory->getId() ?>" data-id="<?php echo $accessory->getFinalPrice() ?>" style="float:right;" onchange="getChoice(this,<?php echo $accessory->getData('entity_id') ?>)">
										<?php foreach($allProducts as $p) {
											if(!$p->isSaleable()) continue;
											$out = $p->getAttributeText($pAtt->getName());
											$sku = $p->getData('entity_id');
											$choicePrice = Mage::getModel('catalog/product')->load($sku)->getFinalPrice();
											$priceDiff = $choicePrice - $accessory->getFinalPrice();
											if($priceDiff > 0){$out = $out." + $".$priceDiff;}
											$frontValues[$out] = $out; ?>
											<option id="<?php echo $p->getData('entity_id'); ?>" data-id="<?php echo $priceDiff; ?>"><?php echo $frontValues[$out] ?></option>
										<?php } ?>
									</select>
								</li>
								<?php } ?>
							</ul>
							<?php } ?>
						<?php } ?>
						<p>
							<span id="p<?php echo $accessory->getData('entity_id') ?>">
								<label for="qty<?php echo $accessory->getProductId() ?>" class="qty-label">Qty</label>
								<input type="number" min="0" name="product[<?php echo $accessory->getProductId() ?>][qty]<?php echo $accessory->getProductId() ?>" id="qty<?php if($accessory->isConfigurable()) {echo $allProducts[0]->getData('entity_id');} else {echo $accessory->getData('entity_id');} ?>" class="input-number" value="0">
							</span>
							<span id="span<?php echo $accessory->getData('entity_id') ?>">
								<span class="price" id="price<?php echo $accessory->getId() ?>"><?php echo Mage::helper('core')->currency($accessory->getFinalPrice(), true, false); ?></span>
								<input type="checkbox" id="<?php if($accessory->isConfigurable()) {echo $allProducts[0]->getData('entity_id');} else {echo $accessory->getData('entity_id');} ?>">
							</span>
						</p>
					</div>
				</div>
				<?php }
			?>
			</li>

			<!-- HARDWARE TAB -->
			<li class="hardware">
			<?php
				$hardwares = Mage::getModel('catalog/category')->load(224)->getProductCollection()
										 ->addAttributeToSelect('*')
										 ->addAttributeToFilter('status', 1)
										 ->addAttributeToFilter('visibility', 4);
				foreach($hardwares as $hardware) { ?>
				<div class="configurator-item-wrapper">
					<div class="configurator-item">
						<div class="img-wrapper">
							<span class="short-desc"><span><?php echo $hardware->getShortDescription(); ?></span></span>
							<img src="<?php echo Mage::helper('catalog/image')->init($hardware, 'small_image')->resize(200,200); ?>" alt="<?php echo $hardware->getName(); ?>">
						</div>
						<h3><?php echo $hardware->getName(); ?></h3>
						<?php if($hardware->isConfigurable()) {
							$attributes = $hardware->getTypeInstance(true)->getConfigurableAttributes($hardware);
							if(count($attributes)) { ?>
							<ul>
								<?php foreach ($attributes as $attribute) {
									$pAtt = $attribute->getProductAttribute();
									$allProducts = $hardware->getTypeInstance(true)->getUsedProducts(null, $hardware);
									$frontValues = array(); ?>
								<li style="padding: 0 1.25em;"><?php echo $pAtt->getFrontendLabel() ?>
									<select id="choice<?php echo $hardware->getId() ?>" data-id="<?php echo $hardware->getFinalPrice() ?>" style="float:right;" onchange="getChoice(this,<?php echo $hardware->getData('entity_id') ?>)">
										<?php foreach($allProducts as $p) {
											if(!$p->isSaleable()) continue;
											$out = $p->getAttributeText($pAtt->getName());
											$sku = $p->getData('entity_id');
											$choicePrice = Mage::getModel('catalog/product')->load($sku)->getFinalPrice();
											$priceDiff = $choicePrice - $hardware->getFinalPrice();
											if($priceDiff > 0){$out = $out." + $".$priceDiff;}
											$frontValues[$out] = $out; ?>
											<option id="<?php echo $p->getData('entity_id'); ?>" data-id="<?php echo $priceDiff; ?>"><?php echo $frontValues[$out] ?></option>
										<?php } ?>
									</select>
								</li>
								<?php } ?>
							</ul>
							<?php } ?>
						<?php } ?>
						<p>
							<span id="p<?php echo $hardware->getData('entity_id') ?>">
								<label for="qty<?php echo $hardware->getProductId() ?>" class="qty-label">Qty</label>
								<input type="number" min="0" name="product[<?php echo $hardware->getProductId() ?>][qty]<?php echo $hardware->getProductId() ?>" id="qty<?php if($hardware->isConfigurable()) {echo $allProducts[0]->getData('entity_id');} else {echo $hardware->getData('entity_id');} ?>" class="input-number" value="0">
							</span>
							<span id="span<?php echo $hardware->getData('entity_id') ?>">
								<span class="price" id="price<?php echo $hardware->getId() ?>"><?php echo Mage::helper('core')->currency($hardware->getFinalPrice(), true, false); ?></span>
								<input type="checkbox" id="<?php if($hardware->isConfigurable()) {echo $allProducts[0]->getData('entity_id');} else {echo $hardware->getData('entity_id');} ?>">
							</span>
						</p>
					</div>
				</div>
				<?php }
			?>
			</li>

		</ul>

</div>

<script>
	jQuery('.cd-slider-nav li').on('click', function(event){
		event.preventDefault();
		var selectedItem = jQuery(this);
		if(!selectedItem.hasClass('selected')) {
			// if it's not already selected
			var selectedPosition = selectedItem.index(),
				activePosition = jQuery('.cd-hero-slider .selected').index();
			if( activePosition < selectedPosition) {
				nextSlide(jQuery('.cd-hero-slider'), jQuery('.cd-slider-nav'), selectedPosition);
			} else {
				prevSlide(jQuery('.cd-hero-slider'), jQuery('.cd-slider-nav'), selectedPosition);
			}
			
			updateNavigationMarker(selectedPosition+1);
		}
	});

	jQuery(document).ready(function(){
		var slidesWrapper = jQuery('.cd-hero-slider');

		//check if a .cd-hero-slider exists in the DOM 
		if ( slidesWrapper.length > 0 ) {
			var primaryNav = jQuery('.cd-primary-nav'),
				sliderNav = jQuery('.cd-slider-nav'),
				navigationMarker = jQuery('.cd-marker'),
				slidesNumber = slidesWrapper.children('li').length,
				visibleSlidePosition = 0,
				autoPlayId,
				autoPlayDelay = 5000;

			//upload videos (if not on mobile devices)
			uploadVideo(slidesWrapper);

			//autoplay slider
			setAutoplay(slidesWrapper, slidesNumber, autoPlayDelay);

			//on mobile - open/close primary navigation clicking/tapping the menu icon
			primaryNav.on('click', function(event){
				if(jQuery(event.target).is('.cd-primary-nav')) jQuery(this).children('ul').toggleClass('is-visible');
			});
			
			//change visible slide
			sliderNav.on('click', 'li', function(event){
				event.preventDefault();
				var selectedItem = jQuery(this);
				if(!selectedItem.hasClass('selected')) {
					// if it's not already selected
					var selectedPosition = selectedItem.index(),
						activePosition = slidesWrapper.find('li.selected').index();
					
					if( activePosition < selectedPosition) {
						nextSlide(slidesWrapper.find('.selected'), slidesWrapper, sliderNav, selectedPosition);
					} else {
						prevSlide(slidesWrapper.find('.selected'), slidesWrapper, sliderNav, selectedPosition);
					}

					//this is used for the autoplay
					visibleSlidePosition = selectedPosition;

					updateSliderNavigation(sliderNav, selectedPosition);
					updateNavigationMarker(navigationMarker, selectedPosition+1);
					//reset autoplay
					setAutoplay(slidesWrapper, slidesNumber, autoPlayDelay);
				}
			});
		}

		function nextSlide(visibleSlide, container, pagination, n){
			visibleSlide.removeClass('selected from-left from-right').addClass('is-moving').one('webkitTransitionEnd otransitionend oTransitionEnd msTransitionEnd transitionend', function(){
				visibleSlide.removeClass('is-moving');
			});

			container.children('li').eq(n).addClass('selected from-right').prevAll().addClass('move-left');
			checkVideo(visibleSlide, container, n);
		}

		function prevSlide(visibleSlide, container, pagination, n){
			visibleSlide.removeClass('selected from-left from-right').addClass('is-moving').one('webkitTransitionEnd otransitionend oTransitionEnd msTransitionEnd transitionend', function(){
				visibleSlide.removeClass('is-moving');
			});

			container.children('li').eq(n).addClass('selected from-left').removeClass('move-left').nextAll().removeClass('move-left');
			checkVideo(visibleSlide, container, n);
		}

		function updateSliderNavigation(pagination, n) {
			var navigationDot = pagination.find('.selected');
			navigationDot.removeClass('selected');
			pagination.find('li').eq(n).addClass('selected');
		}

		function setAutoplay(wrapper, length, delay) {
			if(wrapper.hasClass('autoplay')) {
				clearInterval(autoPlayId);
				autoPlayId = window.setInterval(function(){autoplaySlider(length)}, delay);
			}
		}

		function autoplaySlider(length) {
			if( visibleSlidePosition < length - 1) {
				nextSlide(slidesWrapper.find('.selected'), slidesWrapper, sliderNav, visibleSlidePosition + 1);
				visibleSlidePosition +=1;
			} else {
				prevSlide(slidesWrapper.find('.selected'), slidesWrapper, sliderNav, 0);
				visibleSlidePosition = 0;
			}
			updateNavigationMarker(navigationMarker, visibleSlidePosition+1);
			updateSliderNavigation(sliderNav, visibleSlidePosition);
		}

		function uploadVideo(container) {
			container.find('.cd-bg-video-wrapper').each(function(){
				var videoWrapper = jQuery(this);
				if( videoWrapper.is(':visible') ) {
					// if visible - we are not on a mobile device 
					var	videoUrl = videoWrapper.data('video'),
						video = jQuery('<video loop><source src="'+videoUrl+'.mp4" type="video/mp4" /><source src="'+videoUrl+'.webm" type="video/webm" /></video>');
					video.appendTo(videoWrapper);
					// play video if first slide
					if(videoWrapper.parent('.cd-bg-video.selected').length > 0) video.get(0).play();
				}
			});
		}

		function checkVideo(hiddenSlide, container, n) {
			//check if a video outside the viewport is playing - if yes, pause it
			var hiddenVideo = hiddenSlide.find('video');
			if( hiddenVideo.length > 0 ) hiddenVideo.get(0).pause();

			//check if the select slide contains a video element - if yes, play the video
			var visibleVideo = container.children('li').eq(n).find('video');
			if( visibleVideo.length > 0 ) visibleVideo.get(0).play();
		}

		function updateNavigationMarker(marker, n) {
			marker.removeClassPrefix('item').addClass('item-'+n);
		}

		$.fn.removeClassPrefix = function(prefix) {
			//remove all classes starting with 'prefix'
		    this.each(function(i, el) {
		        var classes = el.className.split(" ").filter(function(c) {
		            return c.lastIndexOf(prefix, 0) !== 0;
		        });
		        el.className = jQuery.trim(classes.join(" "));
		    });
		    return this;
		};
	});

function getChoice(sel, change) {
	checkboxSpanId = 'span'.concat(change);
	quantitySpanId = 'p'.concat(change);

	findSpan = '#'.concat(checkboxSpanId);
	findQty  = '#'.concat(quantitySpanId);

	var inputSelect = jQuery(findSpan).children('input');
	var quantitySelect = jQuery(findQty).children('input');

	var selected  = jQuery(sel).children('option:selected').attr('id');
	var basePrice = parseFloat(jQuery(sel).attr('data-id'));
	var priceDiff = parseFloat(jQuery(sel).children('option:selected').attr('data-id'));
	var newPrice  = basePrice + priceDiff;
	newPrice = '$'.concat(newPrice.toFixed(2));

	console.log(newPrice);

	priceField = '#price'.concat(change);
	priceAfter = jQuery(priceField).html(newPrice);
	console.log(priceField);
	console.log(priceAfter);

	inputSelect.attr('id',selected);
	selectedQty = 'qty'.concat(selected);
	quantitySelect.attr('id',selectedQty);
}

jQuery('input[type="checkbox"]').change(function() {
	console.log(this.id);
	if(this.checked) {
		findQty = '#qty'.concat(this.id);
		qtyVal = jQuery(findQty).val();
	}
});

jQuery('#finalize').on('click',function(event) {
	var products = [];
	var quantities = [];
	var products = jQuery('input:checkbox:checked').map(function () {
		// alert(this.id);
		findQty = '#qty'.concat(this.id);
		qtyVal = jQuery(findQty).val();
		quantities.push(qtyVal);
    	return this.id;
	}).get();
	// var jsonString = JSON.stringify(arr);
	// alert(products);
	// alert(quantities);
	quantitiesGreaterThanZero = true;
	jQuery.each(quantities, function(index,value) {
		if(value == 0) {
			quantitiesGreaterThanZero = false;
		}
	});
	if(products.length > 0 && quantitiesGreaterThanZero) {
		jQuery.ajax({
			type: "POST",
			data: { productsArray   : products,
					quantitiesArray : quantities },
			url: "http://mbs-hanging-systems.com/configurator-addtocart",
			success: function(data) { 
	            window.location.href = 'http://mbs-hanging-systems.com/onepage'
	        }
		});
	} else {
		if(products.length == 0) {
			jQuery('#no-products').show();
		}
	}
});
</script>