<?php 
try {
	$product_ids = $_REQUEST['productsArray'];
	$quantities  = $_REQUEST['quantitiesArray'];
	$n = 0;

	$cart = Mage::getSingleton('checkout/cart')->init();
	foreach($product_ids as $product_id) {
		$product = Mage::getModel('catalog/product')->load($product_id);
		$cart->addProduct($product, $quantities[$n]);
		$n++;
	}
	$cart->save();
	Mage::getSingleton('customer/session')->setCartWasUpdated(true);
	Mage::getSingleton('core/session')->addSuccess('Art Hanging System added to cart successfully. Enjoy!');
} catch (Exception $e) {
	Mage::log($e);
}
?>